export const REQUEST_SEARCH = 'GET/REQUEST_SEARCH';
export const FETCH_BOOKS = 'POST/FETCH_BOOKS';
// export const UPDATE_STARTINDEX = 'PAGINATION_BOOKS/UPDATE_STARTINDEX'; // мб не пригодится
export const ADD_BOOKS = 'PAGINATION_BOOKS/ADD_BOOKS';
export const ADD_MOREBOOKS = 'PAGINATION_BOOKS/ADD_MOREBOOKS'; 
export const ADD_SEARCCONFIG = 'SEARCHING/ADD_SEARCCONFIG';     
export const SEARCCONFIG_UPDATE = 'SEARCHING/SEARCCONFIG_UPDATE'; 
export const GET_FULLBOOK = 'FULLBOOK/GET_FULLBOOK'; 
export const WRITE_FULLBOOK = 'FULLBOOK/WRITE_FULLBOOK'; 

