export const REQUEST_SEARCH = 'GET/REQUEST_SEARCH';
export const FETCH_BOOKS = 'POST/FETCH_BOOKS';
export const UPDATE_STARTINDEX = 'PAGINATION_BOOKS/UPDATE_STARTINDEX'; // мб не пригодится
export const ADD_BOOKS = 'PAGINATION_BOOKS/ADD_BOOKS';
export const ADD_MOREBOOKS = 'PAGINATION_BOOKS/ADD_MOREBOOKS'; 
export const ADD_SEARCHWORD = 'SEARCHING/ADD_SEARCHWORD';